//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : Thu Apr 16 16:40:20 2015
//  generated by     : pvdevelop (C) Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

#include "processviewserver.h"

int show_mask1(PARAM *p);

#endif
